name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Docker Image
        working-directory: ./backend  # This is crucial!
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/be-todo:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/be-todo:latest

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend Docker Image
        working-directory: ./frontend  # This is crucial!
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fe-todo:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fe-todo:latest