name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Build & Push Backend Docker Image
      - name: Build and Push Backend Docker Image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/be-todo:${{ github.sha }} .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/be-todo:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/be-todo:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/be-todo:latest

      # 4. Deploy Backend to Render.com
      - name: Trigger Render Backend Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_WEBHOOK_URL }}

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Build & Push Frontend Docker Image
      - name: Build and Push Frontend Docker Image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fe-todo:${{ github.sha }} .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fe-todo:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fe-todo:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/fe-todo:latest

      # 4. Deploy Frontend to Render.com
      - name: Trigger Render Frontend Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_WEBHOOK_URL }}